title: Einfache Seite

icon: 📝

preset: page

status:
  draft: true
  unlisted:
    label: Nicht gelistet
    text: Die Seite taucht nicht im Menü auf
  listed:
    label: Gelistet
    text: Die Seite taucht im Menü auf

fields:
  text:
    label: Text
    type: textarea
    size: huge

files:
  headline: Headerbilder
  layout: cards
  required: false
  max: 4
