title: Layouts & Blocks

icon: 📝

status:
  draft: true
  unlisted:
    label: Nicht gelistet
    text: Die Seite taucht nicht im Menü auf
  listed:
    label: Gelistet
    text: Die Seite taucht im Menü auf

options:
  changeTemplate:
    - default
    - category


pages: false
tabs:
  content:
    columns:
      left:
        width: 2/3
        fields:
          headline:
            label: Headline
            type: text
            placeholder: "{{ page.title }}"
          text:
            required: true
            autofocus: true
            label: Text
            type: layout
            layouts:
              - "1/1"
              - "1/2, 1/2"
              - "2/3, 1/3"
              - "1/3, 2/3"
              - "1/3, 1/3, 1/3"
              - "2/3, 1/3, 2/3, 1/3"
            fieldsets:
              - heading
              - text
              - list
              - image
              - gallery
              - video
              - code
              - markdown
              - link-button
              - notification-box
              - next-events
              - accordion
              - team-box
              - embed
      right:
        width: 1/3
        sections:

          files:
            type: files
            label: Files

  seo: seo/page
