title: Seite mit Sidebar

icon: 📝

status:
  draft: true
  unlisted:
    label: Nicht gelistet
    text: Die Seite taucht nicht im Menü auf
  listed:
    label: Gelistet
    text: Die Seite taucht im Menü auf

columns:
  top:
    width: 1/1
    sections:
      title:
        type: fields
        fields:
          headline:
            label: Titel
            type: text

      header:
        type: files
        headline: Headerbilder
        layout: cards
        size: tiny
        required: false
        max: 4

  left:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Content
            type: textarea
            size: huge
  right:
    width: 1/3
    sections:
      sidebar:
        type: fields
        fields:
          mybuilder:
            label: Sidebar
            type: builder
            columns: 1
            max: 6
            fieldsets:
              textblock:
                name: Text
                fields:
                  headline:
                    label: Titel
                    type: text
                  content:
                    label: Text
                    type: textarea
              vimeo:
                name: Vimeo Embed
                fields:
                  headline:
                    label: Titel
                    type: text
                  url:
                    label: Video URL
                    type: url

