# The site blueprint must have a title, the title may be different from the file name
# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
title: Welcome Werkstatt

sections:
  pages:
    type: pages
    headline: Seiten

  header:
    type: files
    headline: Globaler Header
    template: headerimage
    layout: cards
    max: 4
    help: Wenn eine Unterseite über keine eigenen Headerbilder verfügt, werden diese globalen Bilder verwendet.






