title: Welcome Werkstatt

tabs:
  content:
    label: Öffentlich
    icon: text
    sections:
      pages:
        templates:
          - category
          - default
          - faq
        type: pages
        headline: Seiten
  internal:
    label: Intern
    icon: circle-nested
    columns:
      - width: 1/1
        sections:
          internal:
            templates:
              - internal
            type: pages
            headline: Intern
  inventory:
    label: Inventar
    icon: box
    columns:
      - width: 1/1
        sections:
          inventory:
            templates:
              - items
            type: pages
            headline: Inventar
            create: false
  seo: seo/site

  global:
    label: Global
    icon: cog
    sections:
      header:
        type: files
        headline: Headerbilder
        template: headerimage
        layout: cards
        max: 4
        help: Wenn eine Unterseite über keine eigenen Headerbilder verfügt, werden diese globalen Bilder verwendet.
      socialmedia:
        type: fields
        fields:
          facebook:
            width: 1/2
            label: Facebook
            type: url
            icon: facebook
          twitter:
            width: 1/2
            label: Twitter
            type: url
            icon: twitter
          instagram:
            width: 1/2
            label: Instagram
            type: url
            icon: instagram
          mastodon:
            width: 1/2
            label: Mastodon
            type: url
            icon: mastodon
          info:
            label: Info
            type: info
            text: |
              Die angegebenen Social-Media-Seiten werden im Footer der Seite als Icon verlinkt. Ein leeres Feld sorgt dafür, dass das zugehörige Icon nicht mehr angezeigt wird.
