# The site blueprint must have a title, the title may be different from the file name
# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
title: Welcome Werkstatt

tabs:
  content:
    label: Inhalte
    icon: text
    sections:
      pages:
        templates:
          - category
          - default
          - noheadline
          - sidebar
          - layouts
        type: pages
        headline: Seiten
  analytics:
    label: Analytics
    icon: globe
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
  inventory:
    label: Inventar
    icon: box
    columns:
      - width: 1/1
        sections:
          inventory:
            templates:
              - inventory
            type: pages
            headline: Inventar
            create: false
  global:
    label: Global
    icon: cog
    sections:
      header:
        type: files
        headline: Headerbilder
        template: headerimage
        layout: cards
        max: 4
        help: Wenn eine Unterseite über keine eigenen Headerbilder verfügt, werden diese globalen Bilder verwendet.
      socialmedia:
        type: fields
        fields:
          facebook:
            width: 1/3
            label: Facebook
            type: url
          twitter:
            width: 1/3
            label: Twitter
            type: url
          instagram:
            width: 1/3
            label: Instagram
            type: url
          info:
            label: Info
            type: info
            text: |
              Die angegebenen Social-Media-Seiten werden im Footer der Seite als Icon verlinkt. Ein leeres Feld sorgt dafür, dass das zugehörige Icon nicht mehr angezeigt wird.
