name: Deploy to Uberspace

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Run a one-line script
        run: ls -la

      - name: Install dependencies
        run: npm i sass

      - name: Compile SASS Stylesheets
        run: ./node_modules/sass/sass.js assets/sass/main.scss assets/css/main.css --style=compressed

      - name: Deploy to Uberspace
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          ARGS: "-avzr"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/welcome/testdeploy"
