name: Deploy to Uberspace

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo from GitHub
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install NPM build dependencies
        run: npm i

      - name: Install Composer dependencies
        run: composer install

      - name: Compile SASS Stylesheets
        run: ./node_modules/sass/sass.js assets/sass/main.scss assets/css/main.css --style=compressed

      - name: Deploy to Uberspace
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          ARGS: "-avzrh --delete-before --exclude '/node_modules/' --exclude '/content/' --exclude '/site/config/' --exclude '/site/accounts/' "
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/welcome/welcome/www.welcome-werkstatt.de"
